name: build-apple-libs

on:
  push:
    tags:
      - v*
  workflow_dispatch: # Allow manual execution

jobs:
  build-lib-apple:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          cargo install cbindgen
          brew install llvm unzip protobuf

      - name: Build Apple XCFramework
        run: |
          ./scripts/build_apple_xcframework.sh

      - name: Zip XCFramework
        run: |
          mv target/apple/release/leaf.xcframework .
          zip -r leaf.xcframework.zip leaf.xcframework

      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaf.xcframework.zip
          path: leaf.xcframework.zip
